services:
  - type: web
    name: github-actions-demo-python-api
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    plan: free